module.exports = {
  AppBar: require('material-ui/lib/app-bar'),
  Avatar: require('material-ui/lib/avatar'),
  Checkbox: require('material-ui/lib/checkbox'),
  CircularProgress: require('material-ui/lib/circular-progress'),
  DatePicker: require('material-ui/lib/date-picker/date-picker'),
  Dialog: require('material-ui/lib/dialog'),
  FloatingActionButton: require('material-ui/lib/floating-action-button'),
  FontIcon: require('material-ui/lib/font-icon'),
  LeftNav: require('material-ui/lib/left-nav'),
  LinearProgress: require('material-ui/lib/linear-progress'),
  List: require('material-ui/lib/lists/list'),
  ListDivider: require('material-ui/lib/lists/list-divider'),
  ListItem: require('material-ui/lib/lists/list-item'),
  MenuItem: require('material-ui/lib/menu/menu-item'),
  Paper: require('material-ui/lib/paper'),
  RaisedButton: require('material-ui/lib/raised-button'),
  SelectField: require('material-ui/lib/select-field'),
  Snackbar: require('material-ui/lib/snackbar'),
  TextField: require('material-ui/lib/text-field'),
  TimePicker: require('material-ui/lib/time-picker'),
  ThemeManager: require('material-ui/lib/styles/theme-manager')
}
